### ISSUE TITLE
atm.setScreen(): unable to find screen 001

### ISSUE THREAD

**Issue by shalikas** [timgabets/electron-atm#9]
Hello, thank you for the nice tool, how to load states, should be they loaded from the host side ? Thank you

**Comment by timgabets** [comment]
Yes, the states and screens must be loaded from the host. To apply the loaded states, you must restart the application after loading (it's a known bug, I'm on my way of fixing it)

**Comment by shalikas** [comment]
Could you please tell which application should be restarted ? Protopas or EATM ? Will it work with DDC protocol or only with NDC?
Thank you

**Comment by timgabets** [comment]
The electron-atm app should be restarted. And it should be NDC only.

**Comment by CrazyMaskSin** [comment]
hello! may I ask  a  question here,  but how can the Application reload the configuration data without restart the App?

**Comment by timgabets** [comment]
Sorry for a late response. No, it's not supportedTG12:18, May 29, 2018, CrazyMaskSin <notifications@github.com>:hello! may I ask  a  question here,  but how can the Application reload the configuration data without restart the App?
